# Generated by Django 5.2.6 on 2025-09-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
            ],
        ),
    ]
